### ISSUE TITLE
Proposal: Encoding CRS information

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogc-feat-geo-json#14]
This proposal describes how to tag coordinate reference system information in a JSON-FG 

Without any other information, for a JSON-FG file the defaults are:

- coordinate reference system: CRS84 or CRS84h (if there is a vertical dimension)
- vertical reference system: whatever the vertical reference system used for CRS84h is (I think it is meters above the ellipsoid).
- temporal reference system: Gregorian

Otherwise:

Reference system values can be specified as:

- a simple URL reference,
- by reference with additional information such as an epoch,
- by value
- or as an array for a compound reference system.

The keys **coord-ref-sys** can be used to assert coordinate reference system information at the collection, feature or value levels.

The **value-ref-sys** key defines a lookup table that allows reference systems to be asserted for simple JSON-FG values. Unlike object values, additional properties (i.e. coord-ref-sys) cannot be added to simple values to assert a reference system.

The **ref-systems** key can be used to declare, at the collection level, a dictionary of reference systems used in the document. Values from this dictionary can be referenced within the document using the aforementioned coord-ref-sys key and relative URL references/JSON pointer values.

https://github.com/opengeospatial/ogc-feat-geo-json/blob/main/proposals/ref-sys.adoc

**Comment by cportele** [comment]
Meeting 2021-08-09: 

* We identified a few small consistency improvements (@pvretano will update).
* Currently no comments on the options.
* Which mechanisms should be included in Part 1? 
* Here is the link to the [related section in the GeoPackage standard](http://www.geopackage.org/spec130/#gpkg_spatial_ref_sys_cols). GPKG uses a dictionary. The CRS is specified on the table/collection level ([link for Features](http://www.geopackage.org/spec130/#gpkg_geometry_columns_cols) and for [tiles](http://www.geopackage.org/spec130/#gpkg_tile_matrix_set_cols)). This is in particular also because of the goal to make GPKG work in an offline context, so the dictionary has to be in the SQLite database.
* How important is it to support offline uses cases in the first part of JSON-FG? The main driver for the SWG charter was API support. For the first release of Part 1 we decided to focus on CRS by reference/identifier (as done by Features Part 2). We should also support also ad-hoc compound CRS (i.e., a an array of CRS URIs). 
* We will also include the epoch option and see if that gets implemented.
* @pvretano will update the proposal and move the parts that we have excluded for now to an "annex" and restrict the technical proposal section to the scope that is identified above.

**Comment by RogerLott** [comment]
@pvretano 

> Without any other information, for a JSON-FG file the defaults are:
. coordinate reference system: CRS84 or CRS84h (if there is a vertical dimension)
. vertical reference system: whatever the vertical reference system used for CRS84h is (I think it is meters above the ellipsoid).

Need to more clearly distinguish between 2D such as CRS84, 2.5D (compound CRS with horizontal and vertical spatial components) and genuine 3D such as CRS84h. There is no global vertical 1D CRS yet available, the nearest currently either an undefined mean sea level (EPSG:5714) or the surface generated by the most recently published global geoid model, EGM2008 (EPSG:3855) although this is about to be replaced with a later model). I don't think either of these is appropriate for a JSON-FG default. The text should read:

Without any other information, for a JSON-FG file the defaults are:

. 2D spatial coordinate reference system: CRS84 (WGS 84 longitude-latitude)
. 3D spatial coordinate reference system: CRS84h  (WGS 84 longitude-latitude-ellipsoidal height)
. temporal coordinate reference system: xxxx [identifier] (Proleptic Gregorian calendar using ISO 8601-1 syntax)

**Comment by cportele** [comment]
Referencing the CRS has been included in the draft spec. We can close this issue and discuss new issues/comments on the draft.
