### ISSUE TITLE
GeoJSON fallback geometries vs. separate geometry properties

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogc-feat-geo-json#21]
Should the specification make any recommendation as to what is expected to be found in a fallback property in GeoJSON compatibility mode (and when to instead use a separate property for a simpler representation of the geometry)?

Should the GeoJSON fallback `geometry` be expected to be the best possible representation of the same geometry found in `where`?

Considering 3D buildings and their footprints as an example, should the `geometry` be MultiPolygons with 3D coordinates which can accurately represent the surfaces for visualization (though it does not allow to associate the faces as solids), while the `where` stores proper JSON F&G polyhedrons, with the footprints stored in a separate property?

Our 3D visualization client understands 3D MultiPolygons representation and renders them as 3D objects. I would expect 3D clients supporting 3D GeoJSON coordinates to be able to render them this way as well -- how else would those be displayed? This may be an outlier in the realms of GeoJSON visualization tools, but if that is the case I think it is because the larger proportion of GeoJSON visualization tools are still only 2D.

Putting the 3D case aside, should fallback properties be a simpler version of the geometry such as a point instead of a polygon? To me that seems to limit the use of a "GeoJSON compatibility" profile, if you request data for maximum compatibility but GeoJSON clients are only capable of displaying points, while JSON F&G clients are able to display polygons.

It is a similar scenario for the 3D buildings case.

**Comment by rob-metalinkage** [comment]
@jerstlouis - good question!  In the Dec 2021 SWG discussion it was proposed that the "geometry" fallback could be a 2D footprint in WGS84 for "the best possible representation" in a "where" property for GeoJSON backwards compatibility.   Use of a centroid rather than a polygon - or a "levels of detail" approach as per GityGML seem fine.  I think explicit use cases should be developed for these scenarios and used to drive some testing.  

This relates to the issue of canonical schemas and the semantics of such properties so consider also #26

**Comment by cportele** [comment]
Meeting 2022-01-22: From a Core perspective we should not constrain the fallback geometry, this would be a task of a community of interest. For draft.1 we will include a statement with an example (with the footprint or representative point geometry as a decision of an information community). @cportele will create a PR.
