### ISSUE TITLE
Add property to detect JSON FG and its version number

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogc-feat-geo-json#70]
It might be useful to have something in the file that fulfills two purposes:
1. Indicate that the file is a JSON FG file (because otherwise you need to scan through all potential properties/extensions)
2. Indicate the implemented version of JSON FG 

This could be two properties, but it could also be a single property.

For the case that it's a single property, I have two ideas in mind:

1. Add a `jsonfg_version` (or similar) property that holds the version number.
  Example: `"jsonfg_version": "0.1.0"`
2. Use the "conformsTo" from OGC APIs and add a link to the versioned JSON FG JSON Schema. 
  Example `"conformsTo": ["https://example.com/jsonfg/v0.1.0/schema.json"]`

**Comment by IvanSanchez** [comment]
I'm partial to the `conformsTo` approach, since it would allow signalling optional conformance classes.

**Comment by cportele** [comment]
Meeting 2022-10-31: Such a hint is valuable and should be added. We are leaning towards the "conformsTo" so that the conformance classes can be identified by the generating and consuming software. The values of "conformsTo" would be the conformance class URIs (e.g. "http://www.opengis.net/spec/json-fg-1/0.1/conf/core"). Of course, parsing the URIs to extract the version number is a bit of a hassle, so maybe the version should also be provided in a separate member? Comments are welcome.

**Comment by cportele** [comment]
Meeting 2023-01-09: We think this is necessary and given that we did not receive any comments, we will move forward with a PR.
